version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV="development"
      - PORT=3000
      - MONGO_URI="mongodb://localhost:27017"
    command: npm start
